---
- name: Handle ACM Managed Cluster Update pre-hook
  hosts: "{{cluster_info['clusterName']}}"
  vars:
    ansible_connection: local
    
  tasks:
    - name: Debug
      ansible.builtin.debug:
        msg: "{{vars}}"
    - name: Debug 2
      ansible.builtin.debug:
        msg: "Test Var: {{ test_var }}"
    - name: Cluster Info
      ansible.builtin.debug:
        msg:
          - "Cluster Name: {{ cluster_info['clusterName'] }}"
          - "Cluster API Server: {{ cluster_info['apiServer'] }}"
    - name: Fail to prevent further execution
      ansible.builtin.fail:
        msg: "Failing the playbook to prevent further execution"
      when: true
